### ISSUE TITLE
everything is fine... not able to find sharing button

### ISSUE THREAD

**Issue by ravijoon** [will-stone/waitanimate#3]
i wanted to tweet it... just my feedback. i like it

**Comment by will-stone** [comment]
Hi @ravijoon, thanks for the compliment. I've never really been that bothered with share buttons, my view has always been that if someone would like to share something they can simply copy the URL and paste it into their own tweet (or use the share buttons of their browser, if they're on mobile). Not to mention that the social network's share widgets are simply a cheap trick to track you around the internet. I'll possibly consider static share buttons... maybe.
